-- 코드를 입력하세요
SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    IFNULL(RV.SCORE, 0)
FROM REST_INFO AS RI
         INNER JOIN
     (SELECT
          REST_ID,
          ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
      FROM REST_REVIEW
      GROUP BY REST_ID)
         AS RV
     ON RI.REST_ID = RV.REST_ID
WHERE
        RI.ADDRESS LIKE '서울%'
ORDER BY RV.SCORE DESC, RI.FAVORITES DESC