SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS ugb
         INNER JOIN USED_GOODS_REPLY AS ugr ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE MONTH(ugb.CREATED_DATE) = 10 AND YEAR(ugb.CREATED_DATE) = 2022
ORDER BY ugr.CREATED_DATE ASC, ugb.TITLE